{
  "severity": "MEDIUM", 
  "created_at": "2019-04-18T21:29:00Z", 
  "description": "The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the ssl_context, ca_certs, or ca_certs_dir argument.", 
  "updated_at": "2019-06-03T17:49:00Z", 
  "packages": [
    {
      "vulnerable_version": "1.22-1", 
      "name": "python-urllib3", 
      "source": "USN", 
      "fixed_version": "1.22-1ubuntu0.18.04.1", 
      "uid": null, 
      "fixed_package": {
        "source": null, 
        "version": "1.22-1ubuntu0.18.04.1", 
        "name": "python-urllib3", 
        "sha256": "cc12d6c983b69b191994e51500e17bf86bf0a06e0a04b65eed175739fccf550f", 
        "sha1": "402612e8f9137c5b6cb228a1fbd34fdff68b7f4a", 
        "md5": "75faee51b7355a8cfab5638ab789ec8c", 
        "arch": "ALL", 
        "filename": "python-urllib3_1.22-1ubuntu0.18.04.1_all.deb"
      }, 
      "vulnerable_package": {
        "source": null, 
        "version": "1.22-1", 
        "name": "python-urllib3", 
        "sha256": "54a5fae3c395e9e7f0f5f9ad7bef86240bc9c04aaa5fc167f1fda59025b2af26", 
        "sha1": "196c99035afdd1504a375476b35a1c4f8572896f", 
        "md5": "460f6f4c5109eb445ce4c73ef8b3a9cd", 
        "arch": "ALL", 
        "filename": "python-urllib3_1.22-1_all.deb"
      }
    }, 
    {
      "vulnerable_version": "1.22-1", 
      "name": "python-urllib3", 
      "source": "USN", 
      "fixed_version": "1.22-1ubuntu0.18.04.1", 
      "uid": null, 
      "fixed_package": {
        "source": "python-urllib3", 
        "version": "1.22-1ubuntu0.18.04.1", 
        "name": "python3-urllib3", 
        "sha256": "c3d9dd2f2fd27b98420ef2d20622675098f29bdb2a863a2367f59c3d6e316700", 
        "sha1": "69694b14ec4869820b870a6bc712412029dbdd10", 
        "md5": "c24c548cd0386ba85c41e21000c02acc", 
        "arch": "ALL", 
        "filename": "python3-urllib3_1.22-1ubuntu0.18.04.1_all.deb"
      }, 
      "vulnerable_package": {
        "source": "python-urllib3", 
        "version": "1.22-1", 
        "name": "python3-urllib3", 
        "sha256": "7c43ae04cc2dc94f66fd03ac1dddc028970c0333e2aa05c297ff17591ab840ca", 
        "sha1": "a9102d34a056396e2eb6029f59c9ef3bda0dc1ad", 
        "md5": "55769b59627ad73f9b642894e5a28f53", 
        "arch": "ALL", 
        "filename": "python3-urllib3_1.22-1_all.deb"
      }
    }
  ], 
  "name": "CVE-2019-11324"
}