{
  "severity": "MEDIUM", 
  "created_at": "2017-08-25T18:29:00Z", 
  "description": "The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack.", 
  "updated_at": "2017-09-08T20:44:00Z", 
  "packages": [
    {
      "vulnerable_version": "1.1+svn4895-1build2", 
      "name": "pykerberos", 
      "source": "USN", 
      "fixed_version": "1.1+svn4895-1+deb6u1build0.12.04.1", 
      "uid": null, 
      "fixed_package": {
        "source": "pykerberos", 
        "version": "1.1+svn4895-1+deb6u1build0.12.04.1", 
        "name": "python-kerberos", 
        "sha256": "710aec9c5e17d324950f1392fbf3a26eb09eb4300f07ceb6dd26b2ed9ee423bd", 
        "sha1": "2303ebd939ff6a4fab389517289a7346a26abda8", 
        "md5": "88f7aa85b9a31b5725a5ab2f0aafd67a", 
        "arch": "I386", 
        "filename": "python-kerberos_1.1+svn4895-1+deb6u1build0.12.04.1_i386.deb"
      }, 
      "vulnerable_package": {
        "source": "pykerberos", 
        "version": "1.1+svn4895-1build2", 
        "name": "python-kerberos", 
        "sha256": "a325f7573901d4b7682a39be0ffce762ae33cb01c1660cc4ff17304524f60e3b", 
        "sha1": "96508fb48e23b93b586f340428f5259b688a3b6d", 
        "md5": "5b492e260fb85db5c8cca501376d65be", 
        "arch": "I386", 
        "filename": "python-kerberos_1.1+svn4895-1build2_i386.deb"
      }
    }, 
    {
      "vulnerable_version": "1.1+svn4895-1build2", 
      "name": "pykerberos", 
      "source": "USN", 
      "fixed_version": "1.1+svn4895-1+deb6u1build0.12.04.1", 
      "uid": null, 
      "fixed_package": {
        "source": "pykerberos", 
        "version": "1.1+svn4895-1+deb6u1build0.12.04.1", 
        "name": "python-kerberos", 
        "sha256": "174f51db959157dc03785b5d760c242627c7710cd4b78425ac49f0c6215bde60", 
        "sha1": "38e664d69eef952443c00b8ed17577889fda8570", 
        "md5": "3a3f54753ce46dced1552b9b7ec6e19e", 
        "arch": "AMD64", 
        "filename": "python-kerberos_1.1+svn4895-1+deb6u1build0.12.04.1_amd64.deb"
      }, 
      "vulnerable_package": {
        "source": "pykerberos", 
        "version": "1.1+svn4895-1build2", 
        "name": "python-kerberos", 
        "sha256": "5d38e0281f38f75e41e657ace221a19a32492405f91e9a80bde731a61fe228b1", 
        "sha1": "3f2446e7ba6d6ba5108697c0ff6e5be262c92a2d", 
        "md5": "a9b278f9f02d3ae8bb417c99b4ceba27", 
        "arch": "AMD64", 
        "filename": "python-kerberos_1.1+svn4895-1build2_amd64.deb"
      }
    }
  ], 
  "name": "CVE-2015-3206"
}